// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOUucMEDrNUanLZjRw6szB9mhpK5ZdXXU',
    appId: '1:231023139911:web:aebc6ab7ed3c4999c26562',
    messagingSenderId: '231023139911',
    projectId: 'lentera-ilmu',
    authDomain: 'lentera-ilmu.firebaseapp.com',
    storageBucket: 'lentera-ilmu.appspot.com',
    measurementId: 'G-XFZQ3D6XWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYeyCVPCSzgH_sDkuBTrYuze2hZSpFCYo',
    appId: '1:231023139911:android:98b49a3b7580df1ac26562',
    messagingSenderId: '231023139911',
    projectId: 'lentera-ilmu',
    storageBucket: 'lentera-ilmu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAe-OtcLZFCgtk58kvrhXGyI6vZwdtmLI',
    appId: '1:231023139911:ios:801a6e60d8c90a3ac26562',
    messagingSenderId: '231023139911',
    projectId: 'lentera-ilmu',
    storageBucket: 'lentera-ilmu.appspot.com',
    iosClientId: '231023139911-ausq3uoukof040j6aq546p8n98rv5rk2.apps.googleusercontent.com',
    iosBundleId: 'id.app.lentera.ilmu',
  );
}
